phrase:
  access_token: 044a2c5a82db84a1acc00b98ee79e1239fd7bd213bc17b85de037c198c0488d6
  
  project_id: ab434927896287462d544ba99e6dec9e

  file_format: html

  push:
    sources:
    - file: ./index_en-US.html
    params: 
     locale_id: 16bfb780da6b0a435d91995091991148

  pull:
    targets:
    - file: ./index_<locale_code>.html
    params:
     locale_id: 97f356c775da9c080c957c54b9d1aaff
      format_option:
       document_id: 3837
