phrase:
  access_token: b7fc60cd08e349735c546d147186900a91ec509bf763e515ea531affb3cd4c29
  project_id: ab434927896287462d544ba99e6dec9e
  file_format: html

  push:
    sources:
    - file: ./newtest_en-US.html
      params: 
       locale_id: 16bfb780da6b0a435d91995091991148

  pull:
    targets:
    - file: ./newtest_<locale_code>.html
      params:
       fallback_locale_id: 16bfb780da6b0a435d91995091991148
       format_options:
         document_id: 4624
